{% set data = load_setup_py_data() %}

package:
  name: thermostate
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install -vv ."
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python >=3.6
    - coolprop >=6.1.0,<6.5
    - pint >=0.9,<1.0
    - matplotlib >=2.0
    - numpy >=1.16

test:
  source_files:
    - tests

  imports:
    - thermostate

  requires:
    - pytest >=3.0.0
    - pytest-cov >=2.3.1

  commands:
    - pytest -vv tests

about:
  home: https://github.com/bryanwweber/thermostate
  license: BSD 3-clause
  license_file: LICENSE.md
  license_family: BSD
  summary: "{{ data['description'] }}"
  description: |
    This package provides a wrapper around [CoolProp](https://github.com/CoolProp/CoolProp)
    that integrates [Pint](https://pint.readthedocs.io) for easy thermodynamic state management
    in any unit system.
  doc_url: https://thermostate.readthedocs.io/
  dev_url: https://github.com/bryanwweber/thermostate
