{% set data = load_setup_py_data() %}

package:
  name: thermostate
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python >=3.5
    - coolprop >=6.1.0,<6.3
    - pint >=0.7.2,<0.9

test:
  imports:
    - thermostate

  requires:
    - pytest >=3.0.0
    - pytest-cov >=2.3.1

  commands:
    - pytest -vv --pyargs thermostate

about:
  home: https://github.com/bryanwweber/thermostate
  license: BSD 3-clause
  license_file: LICENSE.md
  license_family: BSD
  summary: "{{ data['description'] }}"
  description: "{{ data['long_description'] }}"
  doc_url: https://bryanwweber.github.io/thermostate
  dev_url: https://github.com/bryanwweber/thermostate
