name: Python package

on:
  push:
    # Build on tags that look like releases
    tags:
      - v*
    # Build when master is pushed to
    branches:
      - master
  pull_request:
    # Build when a pull request targets master
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions tox-venv
    - name: Test with tox
      run: tox -v
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml

  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-venv
    - run: tox -e flake8

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pandoc from Apt
      run: sudo apt-get install pandoc
    - run: |
        python -m pip install --upgrade pip
        python -m pip install .[docs]
    - run: |
        pushd docs && make html SPHINXOPTS="-W"

  conda-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        activate-environment: ''
        conda-build-version: '3.18'
        auto-activate-base: true
    - run: |
        conda config --append channels conda-forge
      shell: bash -l {0}
    - run: |
        conda install -q anaconda-client conda-verify ripgrep
      shell: bash -l {0}
    - run: |
        conda build conda.recipe
      shell: bash -l {0}
    - run: |
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force $CONDA/conda-bld/*/thermostate*.tar.bz2
      shell: bash -l {0}

  pypi-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - run: python -m pip install --upgrade pip setuptools wheel pep517
    - run: python -m pep517.build --source --binary --out-dir dist/ .
    - name: Publish a Python distribution to PyPI
      # if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@v1.0.0a0
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_PASSWORD }}
        repository_url: https://test.pypi.org/legacy/
